### ISSUE TITLE
Hookem logo updates

### ISSUE THREAD

**Issue by critmcdonald** [statesman/meme#18]
Per Jackie Stone: Apparently when we use the logo it’s always supposed to be the one with “from Austin American-Statesman” underneath it b/c of UT.

White version here, (though you can't see it.)

![hookem_white](https://user-images.githubusercontent.com/4553750/42886922-64acd508-8a6a-11e8-817e-ab5ff6a8c16e.png)

and orange:

![hookem_orange](https://user-images.githubusercontent.com/4553750/42887051-af9fc1e2-8a6a-11e8-81a6-55a48930a7b3.png)

We should also remove the Hookem+ logos.

**Comment by dankeemahill** [comment]
Closed in #19
